apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "ptest2"
  description: "python deploy test for Tanuu (see Egypt)"
  annotations:
    github.com/project-slug: tanuudemo/ptest2
    backstage.io/techdocs-ref: dir:.
spec:
  type: repository
  lifecycle: experimental
  owner: "Daniel"
